site_name: Notatki
theme:
  name: material
  language: pl
  palette:
    primary: lime
  features:
    - navigation.tabs
  theme:
    features:
      - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences